version: "3.8"

services:
  kalman_filtering:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    ports:
      - "8888:8888"
    container_name: kalman_filtering
